//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.Areas.Panel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopDatabaseEntitiesNew : DbContext
    {
        public ShopDatabaseEntitiesNew()
            : base("name=ShopDatabaseEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Attribute> TB_Attribute { get; set; }
        public virtual DbSet<TB_Category> TB_Category { get; set; }
        public virtual DbSet<TB_FUsers> TB_FUsers { get; set; }
        public virtual DbSet<TB_WareHouse> TB_WareHouse { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
        public virtual DbSet<ShowAllAttribute> ShowAllAttributes { get; set; }
        public virtual DbSet<UserShow> UserShows { get; set; }
        public virtual DbSet<WareHouse_View> WareHouse_View { get; set; }
        public virtual DbSet<WishView> WishViews { get; set; }
    }
}
