//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_FUsers
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public Nullable<int> NationalID { get; set; }
        public string Sex { get; set; }
        public string BirthDate { get; set; }
        public string Email { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string MarriageStatus { get; set; }
    }
}
