//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShow
    {
        public string Name { get; set; }
        public int ID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Dimension { get; set; }
        public string Color { get; set; }
        public Nullable<double> Weigh { get; set; }
        public string PackingType { get; set; }
        public string ExtraParts { get; set; }
        public string Description { get; set; }
        public string CatName { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
