//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp1.Areas.Panel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouse_View
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> EntryNo { get; set; }
        public string Time { get; set; }
        public string Date { get; set; }
        public string Name { get; set; }
    }
}
